# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"

reviews:
  profile: "chill"
  path_filters:
    - "!components/ui/**"

auto_review:
  enabled: true
  drafts: false
